name: Build smart contract for Hotmoka 

on:
  push:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          java-version: '16.0.1'
          distribution: 'adopt-hotspot'
          check-latest: true
          
      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v18
        with: 
          repositories: >
            [
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/NFT-Lab/*",
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "${{ secrets.DEPLOY_USERNAME }}",
                "password": "${{ secrets.DEPLOY_ACCESS_TOKEN }}"
              }
            ]

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - uses: actions/checkout@v2
        with:
          repository: Hotmoka/Hotmoka
          path: './hotmoka'
          
      - name: Install Hotmoka
        run: |
          mvn install -f ./hotmoka/pom.xml --projects io-hotmoka-takamaka
        
      - name: Package
        run: mvn clean package -DskipTests=true
        
      - name: Run tests
        run: mvn test
