name: Build ERC721 for Hotmoka 

on:
  push:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          java-version: '16.0.1'
          distribution: 'adopt-hotspot'
          check-latest: true

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Clone and compile Hotmoka
        run: 
          - git clone https://github.com/Hotmoka/hotmoka
          - cd Hotmoka
          - mvn install
          - cd ..

      - name: Package
        run: mvn clean package -DskipTests=true
        
      - name: Run tests
        run: mvn test
